name: runTests


on:
  - push
  - pull_request
jobs:
  docker:
    environment: build
    runs-on: ubuntu-latest
    steps:
      -
        name: RunTests
        run: |
          echo "Hello World"
          echo "test"