name: runTests


on:
  - push
  - pull_request
    # types:
    #   - closed
jobs:
  runTests:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      -
        name: RunTests
        run: |
          echo -e """event: ${{ toJson(github) }}"""
          # echo branch ref: ${{ github.event.pull_request.base.ref }}
          # echo "Hello World"
          # echo "test"
          # sudo gem install bashcov
          # pwd
          # echo "${{ github.workspace }}"
          # ls -l ${{ github.workspace }}
          # # bashcov tests/test_script.sh
          # tests/test_script.sh > TEST-1.xml
      # - name: Publish Test Report
      #   uses: mikepenz/action-junit-report@v3
      #   if: always() # always run even if the previous step fails
      #   with:
      #     report_paths: 'TEST-*.xml'